name: Android Publish Lib

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - 'master'

jobs:
  build_Test_and_publish:

    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Setup Android Environment and permission
        uses: ./.github/actions/setup-android
        with:
          java-version: '17'

      - name: ğŸ“¦ Build Debug AAR
        run: ./gradlew :core:assembleDebug

      - name: â¬†ï¸ Upload Debug AAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: core-debug.aar
          path: ./core/build/outputs/aar/core-debug.aar

      - name: ğŸ“¦ Build Release AAR
        run: ./gradlew :core:assembleRelease

      - name: â¬†ï¸ Upload Release AAR
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: core-release.aar
          path: ./core/build/outputs/aar/core-release.aar


      - name: Build with Gradle
        run: ./gradlew build
